### ISSUE TITLE
Mapping: `'GecureerdeCollectie.bestaatUit` not valid on Activity

### ISSUE THREAD

**Issue by azaroth42** [StadGent/node_service_eventstream-api#44]
The activities have the property `GecureerdeCollectie.bestaatUit` which is defined as `crm:P46_is_composed_of`. The range of P46_is_composed_of is E18 Physical Thing, and E7 Activity is not a physical thing.  See: https://cidoc-crm.org/html/cidoc_crm_v7.1.2.html#P46

Instead the mapping should be crm:P16_used_specific_object to say which objects were used in the exhibit. See: https://cidoc-crm.org/html/cidoc_crm_v7.1.2.html#P16 which is mapped as `Activiteit.gebruiktObject` in the event context.

**Comment by MPParsley** [comment]
Fixed in https://github.com/StadGent/node_service_adlib-backend/pull/90
