### ISSUE TITLE
Mapping: items in GecureerdeCollectie.bestaatUit do not have @type

### ISSUE THREAD

**Issue by azaroth42** [StadGent/node_service_eventstream-api#46]
I can infer from the URI that they are E22_Human-Made_Object instances, but it would be nice if that was explicit in the data.

**Comment by oliviervd** [comment]
fix; 
https://github.com/StadGent/node_service_adlib-backend/pull/90

**Comment by MPParsley** [comment]
Fixed in https://github.com/StadGent/node_service_adlib-backend/pull/90
